// File generated by FlutterFire CLI.
// To refresh, run: flutterfire configure --project=local2local-dev
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show kIsWeb;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    throw UnsupportedError(
        'DefaultFirebaseOptions are not supported for this platform.');
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyAy0umnBYiKPxxAIUT9WLYKG0Fs_zKtMQ8",
    authDomain: 'local2local-dev.firebaseapp.com',
    projectId: 'local2local-dev',
    storageBucket: 'local2local-dev.appspot.com',
    messagingSenderId: '24933902371',
    appId: '1:24933902371:web:5d2a71f084be7b7f1604a3',
    measurementId: 'G-74X1J2J8N7',
  );
}
